# -*- coding: utf-8 -*-
"""Ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nvZlyw0coevE3RAJXtB7dU6VttjcYY0

1. *Calculadora Básica*  
   Escribe un programa que solicite al usuario dos números enteros y luego muestre la suma, resta, multiplicación y división de esos números.
"""

a = int(input("inserte el numero a: "))
b = int(input("inserte el numero b: "))

suma = (a+b)

print("el resultado de su suma es ", suma)

resta = (a-b)

print("el resultado de su resta es ", resta)

multiplicacion = (a*b)

print("el resultado de su multiplicacion es ", multiplicacion)

division = (a/b)

print("el resultado de su division es ", division)

"""2. *Conversión de Temperatura*  
   Crea un programa que convierta una temperatura dada en grados Celsius a Fahrenheit. La fórmula es:  
   \[ \text{Fahrenheit} = \left( \frac{9}{5} \times \text{Celsius} \right) + 32 \]
"""

celcius= float(input("inserte la temperatura en grados celcius: "))

farenheint = (9/5 * celcius) + 32
farenheint2 =round(farenheint, 2)
print("los celcius en farenheint es :", farenheint2)

"""3. *Par o Impar*  
   Escribe un programa que lea un número entero y determine si es par o impar.
"""

entero = int(input("inserte un numero entero:"))

if (entero % 2 == 0):
    print("el numero es par")
else:
    print("el numero es impar")

"""4. *Calculadora de Edad*  
   Solicita al usuario su año de nacimiento y calcula su edad actual. Asegúrate de que el programa sea capaz de manejar la entrada de un año de nacimiento en el futuro y dar un mensaje de error adecuado.
"""

año =int(input("inserte el año en el que usted nacio: "))

if año  >= 2024:
  print("error, ingrese un año de nacimiento valida")
else:
   edad = 2024-año
   print("usted tiene: ", edad)

"""5. *Número Mayor de Tres*  
   Escribe un programa que lea tres números y determine cuál es el mayor.
"""

num1 = float(input("Introduce el primer número: "))
num2 = float(input("Introduce el segundo número: "))
num3 = float(input("Introduce el tercer número: "))


if num1 >= num2 and num1 >= num3:
    mayor = num1
elif num2 >= num1 and num2 >= num3:
    mayor = num2
else:
    mayor = num3


print(f"El número mayor es: {mayor}")

"""6. *Descuento en Tienda*  
   Crea un programa que solicite el precio de un producto y aplique un descuento del 15% si el precio es mayor a $100. Luego, muestra el precio final con el descuento aplicado.
"""

precio = int(input("inserte el precio de un producto :"))

if precio >= 100:
   descuento = precio * 0.15
   descuento2 = precio - descuento
   print("el precio con el descuento es de :" , descuento2)
else:
   print("el precio normal del producto es de :" , precio )

"""7. *Calculadora de Promedio*  
   Escribe un programa que solicite al usuario tres calificaciones y luego calcule y muestre el promedio de esas calificaciones.
"""

nota1 = int(input("inserte su primera nota: "))
nota2 = int(input("inserte su segunda nota: "))
nota3 = int(input("inserte su tercera nota: "))

promedio = (nota1+nota2+nota3)/3
promedio2 = round(promedio,2)

print("el promedio de sus notas es de :", promedio2)

"""8. *Juego de Adivinanza*  
   Programa un juego simple en el que el programa elige un número aleatorio entre 1 y 10, y el usuario tiene que adivinarlo. El programa debe decirle al usuario si su adivinanza es mayor o menor que el número correcto, hasta que adivine correctamente.

"""

import numpy as np

input("Presiona cualquier tecla para empezar el juego: ")

numero_aleatorio = np.random.randint(1, 11)

adivinanza = int(input("Adivina el número (entre 1 y 10): "))


while adivinanza != numero_aleatorio:
    if adivinanza < numero_aleatorio:
        print("Tu adivinanza es menor que el número correcto. ¡Intenta de nuevo!")
    else:
        print("Tu adivinanza es mayor que el número correcto. ¡Intenta de nuevo!")


    adivinanza = int(input("Adivina el número (entre 1 y 10): "))

print(f"¡Felicidades! Adivinaste correctamente. El número era {numero_aleatorio}.")

"""9. *Números del 1 al 10*  
   Escribe un programa que imprima los números del 1 al 10 en orden ascendente usando un bucle for.
"""

for numero in range(1, 11):
    print(numero)

"""10. *Contador de Vocales*  
    Crea un programa que solicite una cadena de texto al usuario y cuente cuántas vocales (a, e, i, o, u) contiene la cadena.
"""

def contar_vocales(texto):
    vocales = 'aeiou'

    contador = 0
    for letra in texto:
        if letra.lower() in vocales:
            contador += 1
    return contador

cadena = input("Ingresa una cadena de texto: ")

numero_vocales = contar_vocales(cadena)

print(f"La cadena contiene {numero_vocales} vocales.")