# -*- coding: utf-8 -*-
"""Taller2JP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fs3iSKyazBbw0P3ZsZpqOCFxysQGJ-wI

:::Desarrolla un programa en C++ que determine el tipo de triángulo (equilátero, isósceles o escaleno) dado el valor de sus tres lados ingresados por el usuario.
Utiliza sentencias if y if-then-else para clasificar el triángulo en función de los valores ingresados.
"""

def tipo_triangulo():

  lado1= float(input("Ingrese el valor del primer lado: "))
  lado2= float(input("Ingrese el valor del segundo lado: "))
  lado3= float(input("Ingrese el valor del tercer lado: "))

  if (lado1 == lado2 == lado3):
     print("El triangulo es equilatero")
  elif (lado1 == lado2 or lado1 ==lado3 or lado2 == lado3):
     print("El triangulo es isoceles")
  else:
     print("El triangulo es escaleno")

tipo_triangulo()

"""o	Escribe un programa que calcule el impuesto sobre la renta de una persona basado en su ingreso anual. El programa debe aplicar diferentes tasas de impuestos dependiendo de la cantidad ingresada, utilizando sentencias if-then-else.
o	Define al menos tres tramos de ingresos con diferentes tasas de impuestos y asegúrate de manejar correctamente los bordes entre los tramos.

"""

def impuesto():

  ingreso = float(input("Inserte su ingreso anual: "))

  if (ingreso <= 10000):
    print("Su impuesto es de un 5%")
    impuesto_añadido = ingreso * 0.05
    impuesto_total = ingreso - impuesto_añadido
  elif (ingreso <= 30000):
    print("Su impuesto es de un 15%")
    impuesto_añadido = ingreso * 0.15
    impuesto_total = ingreso - impuesto_añadido
  elif (ingreso <= 60000):
    print("Su impuesto es de un 30%")
    impuesto_añadido = ingreso * 0.30
    impuesto_total = ingreso - impuesto_añadido
  else:
    print("Su impuesto es de un 45%")
    impuesto_añadido = ingreso * 0.45
    impuesto_total = ingreso - impuesto_añadido


  print("El impuesto añadido es de: ", impuesto_añadido)
  print("El impuesto total que debe pagar es de: ", impuesto_total)

impuesto()

"""o	Crea un programa en C++ que convierta un número del 1 al 7 en el día de la semana correspondiente (1 para Lunes, 2 para Martes, etc.). Utiliza la sentencia switch para implementar esta funcionalidad.
o	Asegúrate de manejar el caso en que el usuario ingrese un número fuera del rango permitido (1-7) y muestra un mensaje de error adecuado.

"""

def dia_semana():

  print("Ingrese un numero del 1 al 7")
  numero = int(input("El numero: "))

  if (numero == 1):
    print("Lunes")

  elif (numero == 2):
    print("Martes")

  elif (numero == 3):
    print("Miercoles")

  elif (numero == 4):
    print("Jueves")

  elif (numero == 5):
    print("Viernes")

  elif (numero == 6):
    print("Sabado")

  elif (numero == 7):
    print("Domingo")

  else:
    print("Error el numero no corresponde a ningun dia de la semana")

dia_semana()

"""o	Desarrolla un programa que reciba una calificación numérica (entre 0 y 100) y la convierta en una calificación en letras (A, B, C, D, F) usando una sentencia switch.
o	Define rangos de notas para cada letra (por ejemplo, 90-100 para A, 80-89 para B, etc.) y asegúrate de manejar correctamente cualquier valor fuera del rango permitido.

"""

def nota():

    nota = int(input("Ingrese su nota: "))

    if (nota <= 100):
      print("Su nota es una A")
    elif (nota <= 89):
      print("Su nota es una B")
    elif (nota <= 79):
      print("Su nota es una C")
    elif (nota <= 69):
      print("Su nota es una D")
    elif (nota <= 59):
      print("Su nota es una F")
    else:
      print("Error la nota que dio no es valida")

nota()

"""o	Crea un programa que calcule el costo de envío de un paquete basado en su peso y destino. Usa estructuras de selección anidadas para determinar el costo. Considera diferentes rangos de peso (por ejemplo, menos de 1 kg, entre 1 y 5 kg, más de 5 kg) y diferentes zonas de destino (nacional, internacional)."""

peso = (int(input("Ingrese el peso del paquete en kg: ")))
destino = (input("Ingrese el destino del paquete: "))

if (peso <= 10):
  print("Usted debera pagar 5000 adicional")
  pagar = 5000
elif (peso <= 50):
  print("Usted debera pagar 10000 adicional")
  pagar = 10000
else:
  print("Usted debera pagar 15000 adicional")
  pagar = 15000

if (destino == "nacional"):
  print("Usted debera pagar 20000 adicional")
  pagar2 = 20000
else:
    print("Usted debera pagar 30000 adicional")
    pagar2 = 30000

total = pagar + pagar2
print("El total a pagar es de: ", total)

"""o	Escribe un programa que evalúe a los candidatos para un puesto de trabajo en función de tres criterios: nivel de experiencia (en años), nivel educativo (secundaria, técnico, universitario), y habilidades (certificación en competencias específicas). Utiliza estructuras de selección anidadas para decidir si un candidato califica para el puesto, es rechazado, o está en consideración.
o	Asegúrate de que el programa pida la información necesaria al usuario y devuelva una decisión basada en los criterios proporcionados.

"""

def evaluar_candidato():
    print("Evaluacion de candidatos para el puesto de trabajo")

    experiencia = int(input("Ingrese los años de experiencia: "))
    nivel_educativo = input("Ingrese el nivel educativo (secundaria, tecnico, universitario): ").lower()
    habilidades_certificadas = input("¿Tiene certificacion en competencias especificas? (si/no): ").lower()

    if experiencia >= 5:
        if nivel_educativo == "universitario":
            if habilidades_certificadas == "si":
                print("Califica para el puesto.")
            else:
                print("Esta en consideracion.")
        elif nivel_educativo == "tecnico":
            print("Esta en consideracion.")
        else:
            print("Rechazado debido al nivel educativo.")
    elif experiencia >= 3:
        if nivel_educativo == "universitario" and habilidades_certificadas == "si":
            print("Esta en consideracion.")
        else:
            print("Rechazado por falta de experiencia o habilidades certificadas.")
    else:
        print("Rechazado por falta de experiencia.")

evaluar_candidato()

"""o	Desarrolla un programa en C++ que simule un sistema básico de gestión de ventas para una tienda. El programa debe permitir al usuario:
	Ingresar la cantidad y el precio de varios productos.
	Calcular el total de la venta.
	Aplicar descuentos basados en el monto total de la compra (por ejemplo, un 5% de descuento para compras mayores a 100 unidades monetarias, 10% para compras mayores a 200, etc.).
	Utiliza estructuras condicionales if-then-else y switch para implementar la lógica de los descuentos y para manejar diferentes tipos de productos y precios.
	Muestra un resumen detallado de la venta, incluyendo la lista de productos comprados, el total bruto, el descuento aplicado, y el total neto.

"""

def gestor_ventas():
    ventas = []
    total = 0

    print("Bienvenido al gestor de tiendas")

    while True:
        nombre_producto = input("Ingrese el nombre del producto (o 'q' para finalizar): ")
        if nombre_producto.lower() == "q":
            break

        cantidad = int(input("Ingrese la cantidad del producto: "))
        precio = float(input("Ingrese el precio del producto: "))

        acumulador = cantidad * precio
        total += acumulador

        if total >= 200:
            descuento = total * 0.10
            descuentofinal = total - descuento
            print("El descuento es del 10%")
        elif total >= 100:
            descuento = total * 0.05
            descuentofinal = total - descuento
            print("El descuento es del 5%")
        else:
            descuento = 0
            descuentofinal = total

        ventas.append(f"{nombre_producto}: {cantidad} x ${precio:.2f} = ${acumulador:.2f}")

    print("\nResumen de compra:")
    for venta in ventas:
        print(venta)

    print(f"\nTotal antes del descuento: ${total:.2f}")
    print(f"Total a pagar después del descuento: ${descuentofinal:.2f}")

gestor_ventas()