# -*- coding: utf-8 -*-
"""Taller1JP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoC2KC1UKYfnrWPXd3xVOhvmnhfwiA-2

2.	Práctica (10 puntos):
o	Desarrolla un algoritmo que, dado un número entero positivo, determine si es un número primo. Implementa el algoritmo en C++.
"""

numero = int(input("Ingrese un numero para comprobar si es primo o no: "))

if numero < 2:
  print("No es primo")
else:
   es_primo = True

for i in range(2, int(numero * 0.5) + 1):
  if numero % i == 0:
    es_primo = False
    break

if es_primo:
    print(f"{numero} es primo")
else:
    print(f"{numero} no es primo")

"""3.	Práctica Comparativa (15 puntos):
o	Escribe un algoritmo en pseudocódigo que calcule el promedio de una lista de 10 números enteros ingresados por el usuario.
o	Implementa este algoritmo tanto en C++ como en Python. Compara ambos lenguajes en términos de facilidad de uso, cantidad de líneas de código, y sintaxis.

"""

notas = []

for i in range(10):
    nota = float(input("Ingrese una nota: "))
    notas.append(nota)

suma = sum(notas)

promedio = suma / 10

print(f"El promedio de las notas es: {promedio}")

"""implementa un programa en C++ que simule un sistema de control de inventarios de una tienda. El programa debe:  Permitir ingresar productos con su nombre, cantidad y precio.  Permitir actualizar el inventario y calcular el total de la venta.  Utiliza variables, constantes, contadores y acumuladores apropiadamente."""

print("Bienvenido a su tienda virtual")

productos = []
total = 0

while True:
    nombre = input("Ingrese el nombre del producto (o 'q' para terminar): ")
    if nombre.lower() == 'q':
        break

    cantidad = int(input("Ingrese la cantidad: "))
    precio = float(input("Ingrese el precio: "))

    subtotal = cantidad * precio
    total += subtotal

    productos.append(f"{nombre}: {cantidad} x ${precio:.2f} = ${subtotal:.2f}")

print("\nResumen de compra:")
for producto in productos:
    print(producto)

print(f"\nTotal a pagar: ${total:.2f}")

"""Desarrolla un programa en python que gestione las calificaciones de un grupo de estudiantes. El programa debe:
	Permitir ingresar el nombre del estudiante y sus calificaciones en tres asignaturas.
	Calcular el promedio de cada estudiante.
	Mostrar una lista de todos los estudiantes con su nombre, promedio y si están aprobados o no (una calificación mayor o igual a 3.0 es aprobada).
	Almacenar la información en un arreglo o vector.
"""

estudiantes = []

while True:
    nombre = input("Ingrese el nombre del estudiante (o 'fin' para terminar): ")
    if nombre.lower() == 'fin':
        break

    suma = 0
    for i in range(3):
        calificacion = float(input(f"Ingrese la calificación de la asignatura {i+1}: "))
        suma += calificacion

    promedio = suma / 3

    estado = "Aprobado" if promedio >= 3.0 else "Reprobado"

    estudiantes.append(f"{nombre}: Promedio {promedio:.2f}, {estado}")

print("\nResultados:")
for estudiante in estudiantes:
    print(estudiante)